print("vivesh")
print("Vivesh Devops Engineer")
print("Vivesh Devops Engineer in Bangalore")
print("Vivesh Devops Engineer in Bangalore, India")
print("Vivesh Devops Engineer in Bangalore, India, Asia")